local loadImages = {}

-- Intro screens
loadImages.titleScreen = love.graphics.newImage("Images/Intro Screens/Title Screen.png")
loadImages.rocStudiosLogo = love.graphics.newImage("Images/Intro Screens/Roc Studios Logo.png")

-- User interface
loadImages.cursor = love.graphics.newImage("Images/User Interface/Cursor.png")
loadImages.cursorHand = love.graphics.newImage("Images/User Interface/Cursor Hand.png")
loadImages.userInterfaceTextBox = love.graphics.newImage("Images/User Interface/User Interface (Text).png")
loadImages.userInterfaceActions = love.graphics.newImage("Images/User Interface/User Interface (Actions).png")

-- Location background images
loadImages.bedroomDark = love.graphics.newImage("Images/Backgrounds/Bedroom (Dark).png")
loadImages.bedroomLight = love.graphics.newImage("Images/Backgrounds/Bedroom (Light).png")
loadImages.carDay = love.graphics.newImage("Images/Backgrounds/Car (Day).png")
loadImages.carEvening = love.graphics.newImage("Images/Backgrounds/Car (Evening).png")
loadImages.carNight = love.graphics.newImage("Images/Backgrounds/Car (Night).png")
loadImages.churchInside = love.graphics.newImage("Images/Backgrounds/Church Inside.png")
loadImages.churchOutside = love.graphics.newImage("Images/Backgrounds/Church Outside.png")
loadImages.classroom = love.graphics.newImage("Images/Backgrounds/Classroom.png")
--loadImages.crawlspace = love.graphics.newImage("Images/Backgrounds/Crawlspace.png")
loadImages.empty = love.graphics.newImage("Images/Backgrounds/Empty.png")
loadImages.emptyRoom = love.graphics.newImage("Images/Backgrounds/Empty Room.png")
loadImages.gasStationBathroom = love.graphics.newImage("Images/Backgrounds/Gas Station Bathroom.png")
loadImages.gasStationOutside = love.graphics.newImage("Images/Backgrounds/Gas Station Outside.png")
loadImages.highway = love.graphics.newImage("Images/Backgrounds/Highway.png")
loadImages.highwayNorthEnd = love.graphics.newImage("Images/Backgrounds/Highway North End.png")
loadImages.kitchen = love.graphics.newImage("Images/Backgrounds/Kitchen.png")
loadImages.livingRoom = love.graphics.newImage("Images/Backgrounds/Living Room.png")
loadImages.mirrorRoom = love.graphics.newImage("Images/Backgrounds/Mirror Room.png")
loadImages.patioLight = love.graphics.newImage("Images/Backgrounds/Patio (Light).png")
loadImages.patioDark = love.graphics.newImage("Images/Backgrounds/Patio (Dark).png")
--loadImages.shed = love.graphics.newImage("Images/Backgrounds/Shed.png")
loadImages.street1 = love.graphics.newImage("Images/Backgrounds/Street 1.png")
loadImages.street2 = love.graphics.newImage("Images/Backgrounds/Street 2.png")
loadImages.street3 = love.graphics.newImage("Images/Backgrounds/Street 3.png")
loadImages.street4 = love.graphics.newImage("Images/Backgrounds/Street 4.png")
loadImages.street5 = love.graphics.newImage("Images/Backgrounds/Street 5.png")
loadImages.street6 = love.graphics.newImage("Images/Backgrounds/Street 6.png")
loadImages.street7 = love.graphics.newImage("Images/Backgrounds/Street 7.png")

-- Game background objects
loadImages.bedroomDoorClosed = love.graphics.newImage("Images/Objects/Bedroom/Bedroom Door Closed.png")
loadImages.bedroomDoorOpen = love.graphics.newImage("Images/Objects/Bedroom/Bedroom Door Open.png")
loadImages.carKey = love.graphics.newImage("Images/Objects/Living Room/Car Key.png")
loadImages.churchDoorOutsideClosed = love.graphics.newImage("Images/Objects/Church Outside/Church Outside Door Closed.png")
loadImages.churchDoorOutsideOpen = love.graphics.newImage("Images/Objects/Church Outside/Church Outside Door Open.png")
loadImages.flashlight = love.graphics.newImage("Images/Objects/Patio/Flashlight.png")
loadImages.mirror = love.graphics.newImage("Images/Objects/Bedroom/Mirror.png")
--loadImages.knife = love.graphics.newImage("Images/Objects/Kitchen/Knife.png")

-- Map objects
loadImages.bedroomMap = love.graphics.newImage("Images/Maps/Bedroom Map.png")
loadImages.carMap = love.graphics.newImage("Images/Maps/Car Map.png")
loadImages.car2Map = love.graphics.newImage("Images/Maps/Car 2 Map.png")
loadImages.car3Map = love.graphics.newImage("Images/Maps/Car 3 Map.png")
loadImages.car4Map = love.graphics.newImage("Images/Maps/Car 4 Map.png")
loadImages.classroomMap = love.graphics.newImage("Images/Maps/Classroom Map.png")
loadImages.churchInsideMap = love.graphics.newImage("Images/Maps/Church Inside Map.png")
loadImages.churchOutsideMap = love.graphics.newImage("Images/Maps/Church Outside Map.png")
--loadImages.crawlspace = love.graphics.newImage("Images/Backgrounds/Crawlspace.png")
loadImages.gasStationBathroomMap = love.graphics.newImage("Images/Maps/Gas Station Bathroom Map.png")
loadImages.gasStationOutsideMap = love.graphics.newImage("Images/Maps/Gas Station Outside Map.png")
loadImages.highwayMap = love.graphics.newImage("Images/Maps/Highway Map.png")
loadImages.highwayNorthEndMap = love.graphics.newImage("Images/Maps/Highway North End Map.png")
loadImages.highwaySouthEndMap = love.graphics.newImage("Images/Maps/Highway South End Map.png")
loadImages.highwayTIntersectionMap = love.graphics.newImage("Images/Maps/Highway T Intersection Map.png")
loadImages.mirrorRoomMap = love.graphics.newImage("Images/Maps/Mirror Room Map.png")
loadImages.sewer1Map = love.graphics.newImage("Images/Maps/Sewer 1 Map.png")
loadImages.street1Map = love.graphics.newImage("Images/Maps/Street 1 Map.png")
loadImages.street2Map = love.graphics.newImage("Images/Maps/Street 2 Map.png")
loadImages.street3Map = love.graphics.newImage("Images/Maps/Street 3 Map.png")
loadImages.street4Map = love.graphics.newImage("Images/Maps/Street 4 Map.png")
loadImages.street5Map = love.graphics.newImage("Images/Maps/Street 5 Map.png")
loadImages.street6Map = love.graphics.newImage("Images/Maps/Street 6 Map.png")
loadImages.street7Map = love.graphics.newImage("Images/Maps/Street 7 Map.png")
loadImages.kitchenMap = love.graphics.newImage("Images/Maps/Kitchen Map.png")
loadImages.livingRoomMap = love.graphics.newImage("Images/Maps/Living Room Map.png")
loadImages.patioMap = love.graphics.newImage("Images/Maps/Patio Map.png")
--loadImages.shedOutsideMap = love.graphics.newImage("Images/Backgrounds/Shed Map.png")

return loadImages